theme: jekyll-theme-cayman
title: axelkennedal.github.io
tagline: Tips, Tutorials & Thoughts for Developers
description: Tips, Tutorials & Thoughts for Developers by Axel Kennedal.

author:
    name: Axel Kennedal

url: https://axelkennedal.github.io
